### ISSUE TITLE
Accessibility - Screen Magnification 

### ISSUE THREAD

**Issue by systemd11** [pop-os/cosmic-comp#942] opened 2024-10-23 21:42 UTC
Please implement screen magnification in COSMIC Desktop / cosmic-comp similar to how KWin handles it, rather than the GNOME-like magnification. The KWin approach is much more responsive & user-friendly.

Feature Details:

- Magnification should work like to KWin's implementation: Smooth scaling with minimal performance hit, avoiding the choppy experience seen in GNOME's magnifier.
- Shortcut to enable/disable screen magnification.
Zoom in/out shortcuts.
- Mouse movement for zoom region control: In GNOME, the mouse cannot be used to adjust the zoom region properly in 3D games, it would be nice to change the magnified region using the mouse in such scenarios too.

**Comment by leviport** [comment] 2024-10-23 21:48
Duplicate of https://github.com/pop-os/cosmic-comp/issues/258

**Closed by leviport** 2024-10-23 21:48 UTC
