### ISSUE TITLE
KDE Connect remote input doesn't work

### ISSUE THREAD

**Issue by Kartonrealista** [pop-os/cosmic-comp#572] opened 2024-06-23 09:07 UTC
The remote mouse and keyboard functions of KDE Connect don't work on cosmic-comp. Tested this on mutter on the same system (Pop on Wayland selected on the login screen) and it worked perfectly.

**Comment by Quackdoc** [comment] 2024-06-23 21:03
duplicate of https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/23

**Closed** 2024-06-23 22:10 UTC

**Comment by Kartonrealista** [comment] 2024-06-23 22:13
Closed since it's a duplicate.
