### ISSUE TITLE
XWayland: scroll wheel not working while mouse is moving

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-comp#159] opened 2023-09-07 16:46 UTC
When running X11 applications, the scroll wheel appears to not be working while the mouse cursor is moving, but works fine if the mouse does not move.

**Comment by ids1024** [comment] 2023-09-07 19:48
I can confirm this is happening with `GDK_BACKEND=x11 gedit` on cosmic-comp but not i3 or sway.

There's no obvious difference in the scroll and motion events I see with `wev`, `xev`, and `xinput test-xi2`. It's not obvious how surface focus or anything could cause issues with this... it's an odd issue.

**Comment by Drakulix** [comment] 2023-09-08 11:39
It might be useful for debugging to start `Xwayland` with `WAYLAND_DEBUG=1` (by patching smithay and wlroots) and compare (very short runs) of this problem between cosmic-comp and sway.

We don't translate cursor events for the X11-protocol in anyway, so the wayland events we are sending to Xwayland must be different in some kind of way. (Probably ordering, maybe related to frame-events, but that is all speculation at this point.)

**Comment by ids1024** [comment] 2023-09-08 16:37
Looks like the order of events is different, and it seems to be fixed with https://github.com/Smithay/smithay/pull/1125, and moving `relative_motion` before `motion`.

For relative motion, it was generating `motion`, then `frame`, then `relative_motion`. I guess they should be in the same frame? May need to clean up the API there. Particularly since pointer constraints may generate `relative_motion` but not `motion`, which would result in having no `frame`.

**Closed** 2023-09-08 18:48 UTC
