### ISSUE TITLE
Cosmic-comp fails to start on Asahi: `Failed to initialize drm device for: /dev/dri/card1`

### ISSUE THREAD

**Issue by shaunsingh** [pop-os/cosmic-comp#68] opened 2023-02-04 19:12 UTC
From what I understand this is because the connectors are associated with different drm device than renderers on these mobile-esque gpus, I believe this is the same issue as https://github.com/Smithay/smithay/issues/678 but I'm not sure

Sway and river (wlroots based) launch just fine for reference, while smithay's anvil results in a similar error

Ran using nix with `nix run github:pop-os/cosmic-comp`

Heres the log output
```
warning: Using saved setting for 'extra-substituters = https://nix-community.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=' from ~/.local/share/nix/trusted-settings.json.
warning: ignoring untrusted substituter 'https://nix-community.cachix.org'
Feb 04 19:06:57.778 INFO Version: 0.1.0
Feb 04 19:06:57.778 INFO Cosmic starting up!
Feb 04 19:06:57.778 INFO Created new socket, wayland_socket: wayland-1
Feb 04 19:06:57.778 INFO Listening on "wayland-1"
Feb 04 19:06:57.833 INFO Initializing a libinput backend, smithay_module: backend_libinput
Feb 04 19:06:57.840 INFO Trying to initialize EGLDevice { inner: 0xaaab13fc5400, device_extensions: ["EGL_EXT_device_drm", "EGL_EXT_device_drm_render_node"] } from renderD128
Feb 04 19:06:57.840 INFO Successfully selected EGL platform: PLATFORM_DEVICE_EXT, platform: EGLPlatform { platform_name: "PLATFORM_DEVICE_EXT", required_extensions: ["EGL_EXT_platform_device"] }, smithay_module: backend_egl
Feb 04 19:06:57.877 INFO EGL Initialized, smithay_module: backend_egl
Feb 04 19:06:57.877 INFO EGL Version: (1, 4), smithay_module: backend_egl
Feb 04 19:06:57.877 INFO Supported EGL display extensions: ["EGL_ANDROID_blob_cache", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_context_flush_control", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image_base", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: backend_egl
Feb 04 19:06:57.878 INFO EGL context created, smithay_module: backend_egl
Feb 04 19:06:57.879 INFO Initializing OpenGL ES Renderer, smithay_module: renderer_gles2
Feb 04 19:06:57.880 INFO GL Version: "OpenGL ES 2.0 Mesa 23.0.0-devel", smithay_module: renderer_gles2
Feb 04 19:06:57.880 INFO GL Vendor: "Asahi", smithay_module: renderer_gles2
Feb 04 19:06:57.880 INFO GL Renderer: "Apple M1 (G13G B1)", smithay_module: renderer_gles2
Feb 04 19:06:57.880 INFO Supported GL Extensions: ["GL_EXT_blend_minmax", "GL_EXT_multi_draw_arrays", "GL_EXT_texture_filter_anisotropic", "GL_EXT_texture_compression_s3tc", "GL_EXT_texture_compression_dxt1", "GL_EXT_texture_format_BGRA8888", "GL_OES_compressed_ETC1_RGB8_texture", "GL_OES_depth24", "GL_OES_element_index_uint", "GL_OES_fbo_render_mipmap", "GL_OES_mapbuffer", "GL_OES_rgb8_rgba8", "GL_OES_standard_derivatives", "GL_OES_stencil8", "GL_OES_texture_3D", "GL_OES_texture_float", "GL_OES_texture_float_linear", "GL_OES_texture_half_float", "GL_OES_texture_half_float_linear", "GL_OES_texture_npot", "GL_OES_vertex_half_float", "GL_EXT_draw_instanced", "GL_OES_EGL_image", "GL_OES_depth_texture", "GL_OES_packed_depth_stencil", "GL_EXT_texture_type_2_10_10_10_REV", "GL_OES_get_program_binary", "GL_APPLE_texture_max_level", "GL_EXT_discard_framebuffer", "GL_EXT_read_format_bgra", "GL_NV_pack_subimage", "GL_EXT_frag_depth", "GL_NV_fbo_color_attachments", "GL_OES_EGL_image_external", "GL_OES_EGL_sync", "GL_OES_vertex_array_object", "GL_ANGLE_pack_reverse_row_order", "GL_ANGLE_texture_compression_dxt3", "GL_ANGLE_texture_compression_dxt5", "GL_EXT_occlusion_query_boolean", "GL_EXT_texture_rg", "GL_EXT_unpack_subimage", "GL_NV_draw_buffers", "GL_NV_read_buffer", "GL_NV_read_depth", "GL_NV_read_depth_stencil", "GL_NV_read_stencil", "GL_EXT_draw_buffers", "GL_EXT_map_buffer_range", "GL_KHR_debug", "GL_KHR_texture_compression_astc_ldr", "GL_NV_pixel_buffer_object", "GL_OES_depth_texture_cube_map", "GL_OES_required_internalformat", "GL_OES_surfaceless_context", "GL_EXT_debug_label", "GL_EXT_separate_shader_objects", "GL_EXT_compressed_ETC1_RGB8_sub_texture", "GL_EXT_draw_elements_base_vertex", "GL_EXT_texture_border_clamp", "GL_KHR_context_flush_control", "GL_OES_draw_elements_base_vertex", "GL_OES_texture_border_clamp", "GL_KHR_no_error", "GL_KHR_texture_compression_astc_sliced_3d", "GL_EXT_texture_compression_s3tc_srgb", "GL_KHR_parallel_shader_compile", "GL_EXT_depth_clamp", "GL_MESA_bgra", ""], smithay_module: renderer_gles2
Feb 04 19:06:57.892 INFO Using renderD128 as primary gpu for rendering
Feb 04 19:06:57.892 INFO Starting XWayland, smithay_module: XWayland
Feb 04 19:06:57.894 WARN Unable to become drm master, assuming unprivileged mode, smithay_module: backend_drm
Feb 04 19:06:57.894 INFO DrmDevice initializing, smithay_module: backend_drm
Feb 04 19:06:57.899 INFO Successfully selected EGL platform: PLATFORM_GBM_KHR, platform: EGLPlatform { platform_name: "PLATFORM_GBM_KHR", required_extensions: ["EGL_KHR_platform_gbm"] }, smithay_module: backend_egl
Feb 04 19:06:57.899 INFO EGL Initialized, smithay_module: backend_egl
Feb 04 19:06:57.899 INFO EGL Version: (1, 4), smithay_module: backend_egl
Feb 04 19:06:57.900 INFO Supported EGL display extensions: ["EGL_ANDROID_blob_cache", "EGL_EXT_buffer_age", "EGL_EXT_image_dma_buf_import", "EGL_EXT_image_dma_buf_import_modifiers", "EGL_KHR_cl_event2", "EGL_KHR_config_attribs", "EGL_KHR_context_flush_control", "EGL_KHR_create_context", "EGL_KHR_create_context_no_error", "EGL_KHR_fence_sync", "EGL_KHR_get_all_proc_addresses", "EGL_KHR_gl_colorspace", "EGL_KHR_gl_renderbuffer_image", "EGL_KHR_gl_texture_2D_image", "EGL_KHR_gl_texture_3D_image", "EGL_KHR_gl_texture_cubemap_image", "EGL_KHR_image", "EGL_KHR_image_base", "EGL_KHR_image_pixmap", "EGL_KHR_no_config_context", "EGL_KHR_reusable_sync", "EGL_KHR_surfaceless_context", "EGL_EXT_pixel_format_float", "EGL_KHR_wait_sync", "EGL_MESA_configless_context", "EGL_MESA_drm_image", "EGL_MESA_image_dma_buf_export", "EGL_MESA_query_driver", "EGL_WL_bind_wayland_display", ""], smithay_module: backend_egl
Feb 04 19:06:57.900 INFO EGL context created, smithay_module: backend_egl
Feb 04 19:06:57.900 INFO Created new socket, wayland_socket: wayland-1-card2
Feb 04 19:06:57.900 INFO Added socket at wayland-1-card2 for gpu card2
Feb 04 19:06:57.901 WARN Failed to initialize output: The graphics api has found no node matching DrmNode { dev: 57858, ty: Primary }
Feb 04 19:06:57.903 WARN Unable to become drm master, assuming unprivileged mode, smithay_module: backend_drm
Feb 04 19:06:57.903 INFO DrmDevice initializing, smithay_module: backend_drm
Feb 04 19:06:57.903 INFO Dropping device: Some("/dev/dri/card1"), smithay_module: backend_drm
Feb 04 19:06:57.907 INFO Shutting down XWayland., smithay_module: XWayland
Feb 04 19:06:57.907 INFO Cleaning up X11 lock., smithay_module: XWayland
Error: Failed to add drm device: /dev/dri/card1

Caused by:
    0: Failed to initialize drm device for: /dev/dri/card1
    1: DRM access error: Error loading resource handles on device `Some("/dev/dri/card1")` (unknown system error: EOPNOTSUPP: Operation not supported on transport endpoint)
    2: unknown system error: EOPNOTSUPP: Operation not supported on transport endpoint
(EE) could not connect to wayland server
```

**Comment by Drakulix** [comment] 2023-02-04 19:18
Yeah, this a duplicate of https://github.com/pop-os/cosmic-comp/issues/8 and https://github.com/Smithay/smithay/issues/678.

We are aware of this, this is an issue affecting all drm drivers utilizing `kmsro`. Fixes will happen, but I cannot give you an estimate for it.

A proper solution would be mesa fixing https://gitlab.freedesktop.org/mesa/mesa/-/issues/5591, which *should* make cosmic-comp (and everything based on smithay) work right out of the box.

But the code path sway chooses insteam, utilizing the `EGL_GBM_PLATFORM` is a valid workaround and has already been prototyped for smithay: https://github.com/Smithay/smithay/pull/842/commits/3917359626f76e2484743808822851dcf68ccaaf

**Comment by Drakulix** [comment] 2024-01-02 17:19
This has been solved for months (at least for Asahi systems). Sorry for not updating this earlier!

**Closed by Drakulix** 2024-01-02 17:19 UTC
