### ISSUE TITLE
X11 Menus Can Go Off-Screen

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-comp#177] opened 2023-09-22 18:37 UTC
![application_menus_off_screen](https://github.com/pop-os/cosmic-comp/assets/3430283/e864bd4d-2526-4420-bdf9-6edf3f6d0bf7)

**Comment by Drakulix** [comment] 2023-09-22 19:17
Did this happen in a multi-monitor situation, where the window was visible on another output? Or did it go completely off any screen?

I am not sure, what we can do here, because Xwayland should already have all information, but I will look into it.

**Comment by WatchMkr** [comment] 2023-10-10 20:37
This occurs on a single display or multiple. Tested with the ws-refactor branch today and the menu is still off screen. In GNOME/Mutter, the menu shows up to the left of the first menu instead of right.

**Comment by Drakulix** [comment] 2023-10-10 21:32
Couldn't reproduce with Inkscape, will try with Chrome.

**Comment by Drakulix** [comment] 2023-10-12 11:07
This was actually a wayland-related problem. I was only able to reproduce this with chrome running with the wayland backend enabled (check if `chrome://flags` lists "Preferred Ozone platform" as `Default` or `Wayland` instead of `X11`).

But this was a general bug with sub-menu popups not correctly in-cooperating their parent-popups position, when calculating offsets. Should be fixed in https://github.com/pop-os/cosmic-comp/pull/194/commits/cb1381b5a02ee5b21953019ac31b11cb3b2adae8 in the ws-refactor branch.

**Closed** 2023-10-26 17:25 UTC
