### ISSUE TITLE
Steam ignores tiling

### ISSUE THREAD

**Issue by nonetrix** [pop-os/cosmic-comp#706] opened 2024-08-09 23:12 UTC
I am on the Cosmic alpha iso have noticed that Steam ignores my tiling setting no matter what I do, I have rebooted multiple times still same thing seems to be completely ignoring it for some reason unlike Hyprland or Sway for example. Val-- PopOS please fix 
![screenshot-2024-08-09-23-10-31](https://github.com/user-attachments/assets/bbc3573a-7974-4e4a-b4ef-54ae9afa959f)
Also there doesn't seem to be a key binding to switch a window to floating or tiling or I can't find it :/

**Comment by phen0mX** [comment] 2024-08-10 09:22
The keybind you are looking for is in your screenshot.
It's 'Super + G' to switch from floating to tiling.

**Comment by leviport** [comment] 2024-08-12 11:25
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/497

**Closed by leviport** 2024-08-12 11:25 UTC

**Comment by nonetrix** [comment] 2024-08-12 16:22
But why exactly is it there? I've used Steam titled for like forever and had no issues, is there something broken I'm missing?

**Comment by mmstick** [comment] 2024-08-12 16:51
Steam dialog windows do not support informing the window manager that they are dialogs, so the compositor can only make an educated guess about whether to tile based on the dimensions of the window. Currently, it's disabled by default because the user experience is very poor when dialog windows pop up and get tiled alongside the main window.
