### ISSUE TITLE
[Feature request] Addition of window opening on workspace....

### ISSUE THREAD

**Issue by HaraldWik** [pop-os/cosmic-comp#936] opened 2024-10-21 14:12 UTC
So what I mean is lets say you open a window/app in workspace 1 and then you move to workspace 2, then it will open there, because its the current workspace. So what I whould like is if the apps remember in which workspace they were opened in!

**Comment by leviport** [comment] 2024-10-21 15:06
duplicate of https://github.com/pop-os/cosmic-epoch/issues/908

**Closed by leviport** 2024-10-21 15:06 UTC
