### ISSUE TITLE
High CPU usage when visualing a pdf with Firefox

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-comp#421] opened 2024-04-12 16:59 UTC
- Gnome 46

![Capture d’écran du 2024-04-12 18-48-18](https://github.com/pop-os/cosmic-comp/assets/78230769/71946956-183e-4247-a057-3ac10889430c)

- Cosmic

![screenshot-2024-04-12-16-50-54](https://github.com/pop-os/cosmic-comp/assets/78230769/a7da6bdf-4be6-468f-be54-7d9790fd7438)

As you can see, firefox is at ~1.5% against 0.19% on Gnome
And compositor is at ~5% against 0.42% for mutter

I'm using Fedora 40, so i suppose this is the wayland version of Firefox.

Note that this only happens with pdf. With "normal" web pages, CPU usage is back to an acceptable value.

**Comment by ids1024** [comment] 2024-04-17 20:40
Interesting. It seems I can reproduce this, and also see higher CPU usage when Firefox is displaying a PDF; but I don't know what the pdf viewer would be doing to have this impact. (Lots of subsurfaces for some reason? Large numbers of some particular Wayland request?)

**Comment by ids1024** [comment] 2024-04-17 20:56
Maybe this is webgl in general, not specifically pdf.js.

It seems all its doing is requesting a frame callback and committing the surface every frame (without attaching a new buffer). While it looks like for a regular page, it doesn't request a frame callback when there's nothing that's changed?

So probably a sign that optimization is needed in general; and better handling of commits that don't change the buffer.

**Comment by wiiznokes** [comment] 2024-04-17 21:01
I think this bug also trigger with images

**Comment by wiiznokes** [comment] 2024-04-17 21:01
I think this bug also trigger with images

**Comment by ids1024** [comment] 2024-05-01 21:33
Modifying https://github.com/Smithay/wayland-rs/blob/master/wayland-client/examples/simple_window.rs to request frames and then commit without changes reproduces this as well.

```diff
diff --git a/wayland-client/examples/simple_window.rs b/wayland-client/examples/simple_window.rs
index d5269e8e7..cc6eaed0c 100644
--- a/wayland-client/examples/simple_window.rs
+++ b/wayland-client/examples/simple_window.rs
@@ -3,8 +3,8 @@ use std::{fs::File, os::unix::prelude::AsFd};
 use wayland_client::{
     delegate_noop,
     protocol::{
-        wl_buffer, wl_compositor, wl_keyboard, wl_registry, wl_seat, wl_shm, wl_shm_pool,
-        wl_surface,
+        wl_buffer, wl_callback, wl_compositor, wl_keyboard, wl_registry, wl_seat, wl_shm,
+        wl_shm_pool, wl_surface,
     },
     Connection, Dispatch, QueueHandle, WEnum,
 };
@@ -88,6 +88,7 @@ impl Dispatch<wl_registry::WlRegistry, ()> for State {
                     if state.configured {
                         let surface = state.base_surface.as_ref().unwrap();
                         surface.attach(Some(&buffer), 0, 0);
+                        surface.frame(qh, ());
                         surface.commit();
                     }
                 }
@@ -139,6 +140,7 @@ impl State {
         let toplevel = xdg_surface.get_toplevel(qh, ());
         toplevel.set_title("A fantastic window!".into());

+        base_surface.frame(qh, ());
         base_surface.commit();

         self.xdg_surface = Some((xdg_surface, toplevel));
@@ -167,7 +169,7 @@ impl Dispatch<xdg_surface::XdgSurface, ()> for State {
         event: xdg_surface::Event,
         _: &(),
         _: &Connection,
-        _: &QueueHandle<Self>,
+        qh: &QueueHandle<Self>,
     ) {
         if let xdg_surface::Event::Configure { serial, .. } = event {
             xdg_surface.ack_configure(serial);
@@ -175,6 +177,7 @@ impl Dispatch<xdg_surface::XdgSurface, ()> for State {
             let surface = state.base_surface.as_ref().unwrap();
             if let Some(ref buffer) = state.buffer {
                 surface.attach(Some(buffer), 0, 0);
+                surface.frame(qh, ());
                 surface.commit();
             }
         }
@@ -230,3 +233,18 @@ impl Dispatch<wl_keyboard::WlKeyboard, ()> for State {
         }
     }
 }
+
+impl Dispatch<wl_callback::WlCallback, ()> for State {
+    fn event(
+        state: &mut Self,
+        _: &wl_callback::WlCallback,
+        _event: wl_callback::Event,
+        _: &(),
+        _: &Connection,
+        qh: &QueueHandle<Self>,
+    ) {
+        let surface = state.base_surface.as_ref().unwrap();
+        surface.frame(qh, ());
+        surface.commit();
+    }
+}
```

**Comment by ids1024** [comment] 2024-05-01 21:37
It looks like it's getting a `frame` callback roughly every 10µs.

So empty commits are sending a frame callback too soon, without waiting for vsync.

**Comment by ids1024** [comment] 2024-05-01 21:54
Or that seems similar on sway, and gnome-shell? And running that example shows somewhat high CPU usage in both.

Maybe something Firefox should improve. But this definitely should have lower overhead in cosmic-comp as well.

**Comment by ids1024** [comment] 2024-05-03 01:10
Using `cargo-flamegraph` and `tracy`, it looks like the time spent in `CompositorHandler::commit` itself, at least, is mostly calling `element_for_surface` and `visible_output_for_surface`. So that's something that could definitely be optimized. Though it may be queuing something later that consumes more CPU.

**Comment by ids1024** [comment] 2024-05-03 01:53
Then `perf top` shows `ToplevelSurface::current_state` is a function that's taking a lot of CPU time in this test case, of all things.

**Comment by Drakulix** [comment] 2024-06-20 11:09
Testing seems to confirm this is fixed by the new scheduling logic in https://github.com/pop-os/cosmic-comp/pull/546, which makes sure to only send frame-callbacks once per vblank.

**Closed** 2024-06-26 13:32 UTC
