### ISSUE TITLE
Notifications block Power Menu buttons

### ISSUE THREAD

**Issue by garrettjwilke** [pop-os/cosmic-comp#778] opened 2024-08-26 21:13 UTC
```
0.1~1724426319~22.04~6669548
```
if there are notifications on screen that have not been cleared out, they will block any buttons "above it". for instance, the power menu will show up on top of everything, but the buttons will not be selectable (power off or restart buttons)

video demonstrating the buttons not working with 2 notifications on screen:

https://github.com/user-attachments/assets/e47f8188-f4bb-4a9f-814e-6a74c5cb1137

**Comment by git-f0x** [comment] 2024-09-20 00:12
Seems to behave similarly to #418. Possibly a related issue.

**Comment by jacobgkau** [comment] 2024-10-22 08:11
This is possibly also a duplicate of https://github.com/pop-os/cosmic-comp/issues/698.

**Comment by git-f0x** [comment] 2024-10-22 18:23
This has been fixed by #918.

**Closed** 2024-10-22 19:06 UTC
