### ISSUE TITLE
[Bug] High CPU-usage by Cosmic-Comp

### ISSUE THREAD

**Issue by feikedonia** [pop-os/cosmic-comp#1084] opened 2024-12-19 14:50 UTC
I hope you can do something with this bug report, because I don't really know why it happend...

I started my computer , then Cosmic, half an hour ago, when me fans started blowing... At Idle... which never happens.

htop shows Cosmic comp at 100% cpu-usage, which I think means that one core is at 100% because otherwise it doesn't make sence:

![afbeelding](https://github.com/user-attachments/assets/6df09701-9f1b-420f-87bc-9db7a25f9722)

**Comment by leviport** [comment] 2024-12-19 16:06
duplicate of https://github.com/pop-os/cosmic-comp/issues/972

**Closed by leviport** 2024-12-19 16:06 UTC
