### ISSUE TITLE
Handle Media buttons

### ISSUE THREAD

**Issue by Snowiiii** [pop-os/cosmic-comp#842] opened 2024-09-08 10:32 UTC
Hey, Im not sure if this issue is the right place for this, But i tested Cosmic today and noticed that my Media buttons which i have on my keyboard do not work. Usally i can pause, skip, go back media content in other DE's but in Cosmic it does not work. If you don't understand which buttons i mean here is an example
![image](https://github.com/user-attachments/assets/240060fe-120a-4058-85a2-b89aee8266a8)

**Comment by Drakulix** [comment] 2024-09-08 20:34
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/895

**Closed by Drakulix** 2024-09-08 20:34 UTC
