### ISSUE TITLE
Cursor keeps the resize icon when moving past window edge

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#390] opened 2024-03-27 18:17 UTC
When the cursor is moved over a window edge, and its resize icon is shown, that icon is kept everywhere outside the window, instead of reverting to its default icon when the window edge is passed.
The cursor reverts to its default icon when it touches a panel, returns to the window or is over another window.
This can make resizing with the mouse a bit difficult.
Probably caused by #380.

**Comment by Drakulix** [comment] 2024-03-28 11:46
Which commit and app does this happen with? Can't reproduce with floating/sticky, client-side or server-side decorated apps.

**Comment by git-f0x** [comment] 2024-03-28 11:57
Happens on the latest available daf669e and in all apps. When the cursor changes to its resize icon, it keeps it everywhere outside the window, unless it touches a panel or different window.

**Comment by Drakulix** [comment] 2024-03-28 12:03
Can reproduce now, this needs cosmic-bg running, which wasn't the case in my debugging setup. (Fascinating..)

**Comment by git-f0x** [comment] 2024-03-28 12:04
Weird...

**Comment by Drakulix** [comment] 2024-03-28 12:08
> Weird...

Currently hypothesis is, that the cosmic-bg surface simply doesn't set any pointer and smithay/cosmic-comp doesn't reset correctly when switching surfaces for focus (instead of switching to an empty focus).

**Comment by git-f0x** [comment] 2024-03-28 12:12
I've also noticed (present for a while) that the cursor sometimes (rarely) gets stuck using an icon (like the hand icon sometimes when using Firefox).

**Comment by Drakulix** [comment] 2024-03-28 12:26
Hypothesis proven, seems to be fixed by using a patched smithay dependencies with https://github.com/Smithay/smithay/pull/1375. I'll update smithay once this is merged and then close this.

**Comment by Drakulix** [comment] 2024-04-02 14:08
Fixed by https://github.com/pop-os/cosmic-comp/commit/e287af1f848915f3169cc02d402afc6843adf448

**Closed by Drakulix** 2024-04-02 14:08 UTC
