### ISSUE TITLE
`Super` + `/` stops working

### ISSUE THREAD

**Issue by n3m0-22** [pop-os/cosmic-comp#112] opened 2023-05-22 23:29 UTC
I have seen `Super` + `/` stop opening Launcher on several occasions, and the session needs to be restarted for it to work again.

**Comment by Drakulix** [comment] 2023-05-23 09:48
It would be helpful to figure out, if this is a cosmic-comp issue or a cosmic-launcher issue.
Next time this happens, can you verify the cosmic-launcher daemon is still running with `pgrep cosmic-launcher` (and see if the command returns a PID).
Additionally the output of `journalctl --user _EXE=/usr/bin/cosmic-session | grep cosmic-launcher` might be helpful to nail down the cause.

**Comment by mmstick** [comment] 2023-05-23 12:52
Killing cosmic-launcher can get the shortcut working again

**Comment by Drakulix** [comment] 2023-05-23 17:23
> Killing cosmic-launcher can get the shortcut working again

That would be an indication, that this is an issue of the launcher. Killing it, would lead to cosmic-session restarting it. If it works afterwards cosmic-comp likely processed the shortcut just fine, but the daemon is not reacting.

**Comment by mmstick** [comment] 2023-05-23 21:08
This may be fixed by https://github.com/pop-os/cosmic-launcher/pull/39 but I'll need to keep testing to be certain.

**Comment by n3m0-22** [comment] 2023-05-23 21:11
I take a look on my end too. The strange thing is I have not been able to get it to happen even once today.

**Comment by mmstick** [comment] 2023-05-23 21:12
I noticed it happening when using certain plugins, like the `recent` plugin

**Comment by n3m0-22** [comment] 2023-05-23 21:13
Thanks, I'll try that.

**Comment by XV-02** [comment] 2024-02-22 20:11
I haven't seen any issue with launcher reliability for months. Looking at this again recently, I'm not seeing any particular difficulty with `Super + /` either. I believe this is resolved, and closing it accordingly.

**Closed by XV-02** 2024-02-22 20:11 UTC
