### ISSUE TITLE
Crash when moving window to (non-existent) workspace

### ISSUE THREAD

**Issue by miquella** [pop-os/cosmic-comp#846] opened 2024-09-09 04:30 UTC
While moving windows around, I accidentally tried moving the window up to a non-existent workspace, which appears to have crashed the compositor.

1. Using tiled windows
2. Focused on a window tiled to the top-left of the screen
3. Attempted Super+Shift+Up
4. Crashed the compositor, closing all applications

I would have expected it to either:
1. Do nothing
2. Create a new workspace

```console
$ apt info cosmic-comp
Package: cosmic-comp
Version: 0.1~1725475842~24.04~79ae56c
...
```

<details>
<summary><code>cosmic-comp</code> error</summary>
<pre>
Sep 08 22:00:02 agnes cosmic-comp[1770]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:2833
                                            0: <unknown>
                                            1: <unknown>
                                            2: <unknown>
                                            3: <unknown>
                                            4: <unknown>
                                            5: <unknown>
                                            6: <unknown>
                                            7: <unknown>
                                            8: <unknown>
                                            9: <unknown>
                                           10: <unknown>
                                           11: <unknown>
                                           12: <unknown>
                                           13: <unknown>
                                           14: <unknown>
                                           15: <unknown>
                                           16: <unknown>
                                           17: <unknown>
                                           18: <unknown>
                                           19: <unknown>
                                           20: <unknown>
                                           21: __libc_start_main
                                           22: <unknown>
Sep 08 22:00:03 agnes cosmic-comp[1770]: [EGL] 0x3001 (NOT_INITIALIZED) eglDestroySync: EGL_NOT_INITIALIZED error: In eglDestroySync: EGLDisplay (0x59756a8e0e30) not intiialized
</pre>
</details>

<details>
<summary>Additional <code>cosmic-panel</code> errors</summary>
<pre>
Sep 08 22:00:03 agnes cosmic-session[1764]: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes xdg-desktop-por[2039]: Error reading events from display: Broken pipe
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletAudio: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletAudio: thread '<unnamed>' panicked at /build/cosmic-applets-9800Gw/cosmic-applets-0.1.0~1725375368~24.04~0b53634/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletAudio: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletAudio: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletBluetooth: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletBluetooth: thread '<unnamed>' panicked at /build/cosmic-applets-9800Gw/cosmic-applets-0.1.0~1725375368~24.04~0b53634/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletBluetooth: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletBluetooth: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTime: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTime: thread '<unnamed>' panicked at /build/cosmic-applets-9800Gw/cosmic-applets-0.1.0~1725375368~24.04~0b53634/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTime: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTime: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNetwork: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNetwork: thread '<unnamed>' panicked at /build/cosmic-applets-9800Gw/cosmic-applets-0.1.0~1725375368~24.04~0b53634/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNetwork: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNetwork: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: thread '<unnamed>' panicked at cosmic-applet-minimize/src/wayland_handler.rs:507:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNotifications: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNotifications: thread '<unnamed>' panicked at /build/cosmic-applets-9800Gw/cosmic-applets-0.1.0~1725375368~24.04~0b53634/vendor/libcosmic/src/applet/token/wayland_handler.rs:174:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNotifications: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNotifications: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTiling: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTiling: thread '<unnamed>' panicked at cosmic-applet-tiling/src/wayland.rs:151:55:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTiling: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTiling: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppList: Io error: Broken pipe (os error 32)
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppList: thread '<unnamed>' panicked at cosmic-app-list/src/wayland_handler.rs:719:50:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppList: called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppList: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTime: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNotifications: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletBluetooth: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletAudio: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletNetwork: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletTiling: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppList: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: thread 'main' panicked at cosmic-applet-minimize/src/lib.rs:125:21:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: Wayland Subscription ended...
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: stack backtrace:
Sep 08 22:00:03 agnes cosmic-panel[1827]: com.system76.CosmicAppletMinimize: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 08 22:00:03 agnes cosmic-panel[1827]: process ' X_MINIMIZE_APPLET=true X_PRIVILEGED_WAYLAND_SOCKET=113 COSMIC_PANEL_NAME=Dock COSMIC_PANEL_SIZE=L COSMIC_PANEL_OUTPUT=DP-1 COSMIC_PANEL_ANCHOR=Bottom COSMIC_PANEL_BACKGROUND=ThemeDefault RUST_BACKTRACE=1 WAYLAND_SOCKET=106 cosmic-applet-minimize ' failed with code 101
Sep 08 22:00:03 agnes cosmic-panel[1827]: Exited with error code 101
Sep 08 22:00:03 agnes systemd[1692]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
Sep 08 22:00:03 agnes systemd[1692]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
Sep 08 22:00:03 agnes cosmic-session[1764]: process ' COSMIC_SESSION_SOCK=12 cosmic-comp ' failed with code 101
Sep 08 22:00:03 agnes cosmic-session[1764]: cosmic-comp exited with error code 101
</pre>
</details>

**Comment by man0lis** [comment] 2024-09-09 11:11
I seem to have run into the same problem. At least the stack trace I get shows the same line with an unwrap() as the source of the problem. 

My steps to reproduce:

1. start with fresh cosmic-session
2. open 2 terminals
3. Focus both with Super+U
4. Try to stack them with Super+S
5. Press Super+Left (intention was to focus the Left terminal)

For me cosmic-comp crashes after this sequence of inputs.

My cosmic-comp was build from commit 79ae56c601176f179870f75719416dbabe3d01d9

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:2833
 0: <backtrace::capture::Backtrace as core::default::Default>::default
 1: log_panics::Config::install_panic_hook::{{closure}}
 2: std::panicking::rust_panic_with_hook
 3: std::panicking::begin_panic_handler::{{closure}}
 4: std::sys::backtrace::__rust_end_short_backtrace
 5: rust_begin_unwind
 6: core::panicking::panic_fmt
 7: core::panicking::panic
 8: core::option::unwrap_failed
 9: cosmic_comp::shell::Shell::next_focus
10: cosmic_comp::input::<impl cosmic_comp::state::State>::handle_shortcut_action
11: cosmic_comp::input::<impl cosmic_comp::state::State>::handle_action
12: cosmic_comp::input::<impl cosmic_comp::state::State>::process_input_event
13: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events::{{closure}}
14: <smithay::backend::libinput::LibinputInputBackend as calloop::sources::EventSource>::process_events
15: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
16: calloop::loop_logic::EventLoop<Data>::run
17: cosmic_comp::main
18: std::sys::backtrace::__rust_begin_short_backtrace
19: main
20: __libc_start_call_main
21: __libc_start_main@GLIBC_2.2.5
22: _start
```

**Comment by Drakulix** [comment] 2024-09-09 18:25
Might be fixed by https://github.com/pop-os/cosmic-comp/commit/f0f1db43582649f5adbcb3392cd25092734c04c9

**Comment by hojjatabdollahi** [comment] 2024-09-10 03:34
It did not fix it. Still is happening.

 Version: 0.1~1725905530~24.04~0d048b1

**Comment by Drakulix** [comment] 2024-09-10 18:52
Looks like this was primary an issue of trying to move groups. https://github.com/pop-os/cosmic-comp/commit/b111c9ff486d37395d9fcb3702d71140627e9919 fixes that, but only moves a window of said group at once.

b111c9ff486d37395d9fcb3702d71140627e9919 now finally also addresses that, making it possible to move groups via these shortcuts to over outputs.

**Comment by hojjatabdollahi** [comment] 2024-09-10 21:30
Can confirm. It's fixed now. Thank you.

**Comment by miquella** [comment] 2024-09-28 13:35
I am also no longer able to reproduce the issue. Thank you!

**Closed** 2024-09-28 13:35 UTC
