### ISSUE TITLE
Freeze in Iris driver when Nvidia Vulkan Wgpu client tries to re-create swapchain to handle `suboptimal` present

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-comp#300] opened 2024-02-08 00:06 UTC
I noticed this when applying this patch to wgpu:

```rs.patch
diff --git a/examples/src/framework.rs b/examples/src/framework.rs
index 514fbca92..e986cdb12 100644
--- a/examples/src/framework.rs
+++ b/examples/src/framework.rs
@@ -462,8 +462,14 @@ async fn start<E: Example>(title: &str) {
                             .unwrap()
                             .render(&view, &context.device, &context.queue);

+                        let suboptimal = frame.suboptimal;
+
                         frame.present();

+                        if suboptimal {
+                            surface.get().unwrap().configure(&context.device, surface.config());
+                        }
+
                         window_loop.window.request_redraw();
                     }
                     _ => example.as_mut().unwrap().update(event),
```

Then running `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json WGPU_BACKEND=vulkan cargo run -p wgpu-examples skybox`.

When I open the window on my builtin (Intel) monitor, it works fine. When I move the window to the external (Nvidia) monitor, it tries to re-create the swapchain, and the compositor freezes. It seems to run into the issue I've seen before where Iris loops infinitely when the Nvidia `get_sg_table` call fails. (I guess an issue was never opened for that one, but I've created one now: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10572.)

Looking a `WAYLAND_DEBUG` output, it seems to be using linear AR24 dmabuf in either case. What seems to matter here is `tranche_target_device`. If I modify Smithay to make that always `self.0.main_device`, I don't see any issue. I'm guessing if the `tranche_target_device` is the Nvidia GPU, the driver allocates a buffer that isn't importable by another device?  If so, I'm not sure if this is Nvidia or smithay misusing the dmabuf feedback, or an issue in the design of the protocol. This doesn't seem to happen on Sway (though rendering on the Nvidia outputs is also broken and full of artifacts since it doesn't have proper synchronization.)

I assume we weren't seeing this before since, without re-creating suboptimal swapchains, it was using feedback based on an unmapped window. So it didn't take into account the output.

Presumably Wgpu applications, including Iced, should be handling `suboptimal` like this, but I think I'll refrain from changing anything there while we're seeing this issue...

**Comment by Drakulix** [comment] 2024-02-08 13:59
Right, but the api absolutely allows to try that import. We should figure out, why we do that in the first place, but I guess during the move, it is displayed on both. So the MultiRenderer first tries the direct import and would then fallback to a memory copy.

If the modifier is consistently `LINEAR`, there is not much we can do about that. If we try to import some nvidia specific modifier, then that is our bug.

**Comment by ids1024** [comment] 2024-02-08 15:33
From piping `WAYLAND_DEBUG` output to a file, it seemed to be using linear dmabufs. If it used an Nvidia modifier, Iris should refuse to import it before getting to this point.

So I think when `tranche_target_device` isn't the Nvidia GPU, it creates a buffer that's importable from other GPUs (possibly in main memory or the other GPU; or still on the Nvidia GPU but somehow allocated to be accessible?).

As currently written in the protocol, I think Nvidia is wrong here, and `zwp_linux_buffer_params_v1_create_immed` would be allowed to send a protocol error when the `main_device` fails to import the buffer. The Iris bug is the worse part though; otherwise we could fallback to attempting import on other GPUs. And if `set_target_device` were added, we could know which one to use immediately (and wouldn't be restricted to only supporting buffers importable by the main device).

**Comment by Drakulix** [comment] 2024-02-08 15:44
However this mean we might be able to get away with this in cosmic-comp, if we can check, if the window is visible on any gpu's outputs before updating the `target_device`. But then we also need to make sure we always use the secondary nvidia-gpu to render nvidia outputs, so we never attempt to import such a buffer.. Urgh.

**Comment by ids1024** [comment] 2024-02-08 16:03
The issue happened when I move the Nvidia-rendered surface from my Intel monitor to the external Nvidia monitor, so I think this would be the actual scanout tranche. It isn't a problem when the scanout flag is set but `tranche_target_device` isn't the Nvidia GPU.

> Which is totally valid and shouldn't result in the mesa bug.

In the discussion on the v5 MR, it was suggested that cross-device import like this would often/usually perform worse, so we might not want to do that. But yes, we should be able to do so and either get an import error we can handle, or a successful import that renders correctly. Not an infinite loop.

**Comment by Drakulix** [comment] 2024-02-08 16:08
> It isn't a problem when the scanout flag is set but tranche_target_device isn't the Nvidia GPU.

Right, but that is because the scanout flag is ignored in that case for the nvidia buffer as it needs to be copied anyway.

> In the discussion on the v5 MR, it was suggested that cross-device import like this would often/usually perform worse, so we might not want to do that.

Perform worse than what. Certainly not necessarily than a memory copy, except for cases where this results in migration of the original buffer, which we can't avoid with the current api.

I want to implement better handling of shadow-copies of buffers eventually, but I don't think the default should be to copy via memory. However we could try the other way around and do a new buffer on the intel gpu, import that into the nvidia one and render the original buffer into it... Except nvidia can't render into linear buffers... Which is why we try the reverse of importing the nvidia buffer into the intel gpu in the first place...

**Comment by RyzenDew** [comment] 2024-02-08 19:21
WGPU issue will be solved in a 550 release either at the end of feb or march confirmed by an nvidia dev

**Comment by Drakulix** [comment] 2024-02-19 12:12
Should now also be addressed by https://github.com/pop-os/cosmic-comp/pull/278

**Closed** 2024-03-06 15:53 UTC
