### ISSUE TITLE
Super + Search adds workspace when on 1 workspace

### ISSUE THREAD

**Issue by Nashenas88** [pop-os/cosmic-comp#864] opened 2024-09-14 02:54 UTC
This might be multiple bugs in one.

```
Package: cosmic-comp
Architecture: amd64
Version: 0.1~1726087871~22.04~3e1b352
```

Steps to reproduce:
1. Log in (no windows open at this point)
2. Four-finger swipe to next workspace (notice that the animation goes backwards from normal, and now there's only one workspace, can confirm by clicking on workspaces button and only seeing one)
3. Press Super key to bring up search
4. Press Escape to exit search
5. Click on workspaces button (there's now two workspaces)
6. Click on workspaces button again (closes workspaces list)
7. Move to the second workspace with 4-finger swipe
8. Move back to the first workspace with 4-finger swipe
9. Go to step 2 above

Results of steps 2 and (3+4+5) are really confusing.

**Comment by Nashenas88** [comment] 2024-09-14 02:57
I found another way to reproduce this easily.

1. Move to last workspace
2. Press workspaces button
3. Press super key

You should now see an extra window pop into the workspaces list.

4. Go to step 1

Also, after opening a bunch of these, you can 4-finger swipe randomly to slowly close them one-by-one.

**Comment by Nashenas88** [comment] 2024-09-17 18:12
Here's an example of what that ends up as (is this also worth filing a bug for the display of so many workspaces?)
![screenshot-2024-09-17-18-09-21](https://github.com/user-attachments/assets/9e03fee0-0fdd-4ae6-9364-c0749795bef4)

**Comment by leviport** [comment] 2024-09-17 18:27
I believe this is a duplicate of https://github.com/pop-os/cosmic-workspaces/issues/86

**Closed by leviport** 2024-09-17 18:27 UTC
