### ISSUE TITLE
[BUG] Recent breakage - user session crashes when plugging/unplugging HDMI monitor

### ISSUE THREAD

**Issue by zsilet** [pop-os/cosmic-comp#1043] opened 2024-12-10 00:46 UTC
**Issue/Bug description:**
I am using a 4K TV as a monitor (have been using it for years). When the HDMI connection is broken or established, my user session restarts (I get a bunch of console errors scroll by, then  I'm back to a fresh desktop with all my previously running apps gone. 

After the apparent recovery, I have also observed the following seemingly related issues:
1) Desktop becomes super laggy (unusably so).
2) Panel/dock crashed after a few minutes.

This issue seems to have been introduced sometime between December 5th and December 9th. 
 
I have verified Pop_os 22.04 installation (same computer, different partition, much older popdev:master) works as expected (can unplug/replug HDMI without issues).
 
**Steps to reproduce:**
Any of the following sctions causes the issue to happen:
 - Wake computer from sleep, and then turn on monitor (which had gone to sleep also).
 - Unplug HDMI to external monitor
- Plug in HDMI to external monitor

Started happening since updating this morning, December 9th. Tried rebooting etc, no change. 

**Expected behavior:**
Can hot-plug external monitor without issues. 

**Other notes:**
 This issue seems to have been introduced sometime between December 5th and December 9th. 
 
 I have attached all my software versions as of my most recent update this morning. 
 
 The systemd journal shows the issue, starting at time stamp:
  Dec 09 19:38:47 pop-os cosmic-comp[2615]: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value': src/shell/mod.rs:974

[log.txt](https://github.com/user-attachments/files/18069832/log.txt)
[sys_info_sw_2024-Dec- 9-1245.txt](https://github.com/user-attachments/files/18069833/sys_info_sw_2024-Dec-.9-1245.txt)

**Comment by ctrox** [comment] 2024-12-10 07:39
Can confirm the same issue on Fedora with `1.0.0~alpha.4^git20241205.7829e76-1.fc40`. I just reverted back to `cosmic-comp-1.0.0~alpha.3^git20241202.e3b41c5-1.fc40`, where I can't reproduce it anymore.

**Comment by APCBoston** [comment] 2024-12-12 18:30
Possible duplicate of #906

**Closed** 2024-12-12 19:09 UTC
