### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by rrahl0** [pop-os/cosmic-comp#527] opened 2024-05-31 16:16 UTC
When I am in floating mode, and I have 2 maximized windows in the background, and a terminal in the front, the screen starts to flicker (only the maximized windows are flickering)

**Comment by wash2** [comment] 2024-05-31 16:29
https://github.com/pop-os/cosmic-comp/commit/13e67f3dc2bd14d80de0d200671be70f9fbdc761 should fix this issue

**Comment by rrahl0** [comment] 2024-06-05 10:33
still happening. I am on commit #697ec9e

**Comment by jacobgkau** [comment] 2024-06-26 16:02
This is a duplicate of https://github.com/pop-os/cosmic-comp/issues/526, but it is still happening on current master (9cd553e).

I'm closing as a duplicate to track it in the other issue.

**Closed by jacobgkau** 2024-06-26 16:02 UTC
