### ISSUE TITLE
Testing on Arch Linux

### ISSUE THREAD

**Issue by road2react** [pop-os/cosmic-comp#22] opened 2022-07-13 20:56 UTC
I found this package: https://aur.archlinux.org/packages/cosmic-comp-git

What is the process for testing? I'm open for testing on Wayland, using a hybrid GPU setup (AMD/AMD).

**Comment by Drakulix** [comment] 2022-07-15 10:41
There are currently some testing instructions over on https://github.com/pop-os/cosmic-epoch, that should in principle also work on arch linux.
The package you linked is not created by us and thus not officially supported, but might still work.

You are free to try and play around with it or even contribute to the projects, but we are currently not looking for testing or feedback by users. The project is at such an early state, that there are lots of bugs and missing features, we are well aware of, that just need more time.

**Comment by CatPerson136** [comment] 2022-11-29 21:18
Since I use arch, I could probably test it as well

**Comment by mfdorst** [comment] 2023-02-27 20:38
I just ran into the same thing.

I ran
```
paru -S cosmic-epoch-git
```
and got
```
... (omitted for brevity)
~/.cache/paru/clone/cosmic-epoch-git/src/cosmic-epoch/cosmic-comp ~/.cache/paru/clone/cosmic-epoch-git/src/cosmic-epoch
    Updating git repository `https://github.com/smithay//smithay`
error: failed to load source for dependency `smithay`

Caused by:
  Unable to update https://github.com/smithay//smithay?rev=09e29418e5#09e29418

Caused by:
  object not found - no match for id (09e29418e5d973dd21fc636433cca0b4dc3a17b3); class=Odb (9); code=NotFound (-3)
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'cosmic-epoch-git-r41.75cb3ab-1': 
error: packages failed to build: cosmic-epoch-git-r41.75cb3ab-1
```

**Comment by mfdorst** [comment] 2023-02-27 21:16
I did some digging into the `PKGBUILD` and found that the error is caused by doing `cargo fetch --target x86_64-unknown-linux-gnu`.
I thought maybe the `smithay` dependency was listing a commit that didn't exist anymore, so I tried `cargo update`, and it gave me the same error.

**Comment by jokeyrhyme** [comment] 2023-02-28 00:14
I'd try to reproduce just from the instructions in https://github.com/pop-os/cosmic-epoch/blob/master/README.md , and making sure to double-check that you have the latest submodules e.g. `git submodule update --init --force`

If you can't reproduce from that, then the issue is with the PKGBUILD, so should be reported to that maintainer instead

**Comment by RillonDodgers** [comment] 2023-03-01 19:12
I have tried both ways as well

`yay -S cosmic-epoch-git` results:
```
~/.cache/yay/cosmic-epoch-git/src/cosmic-epoch/cosmic-comp ~/.cache/yay/cosmic-epoch-git/src/cosmic-epoch
    Updating git repository `https://github.com/smithay//smithay`
error: failed to load source for dependency `smithay`

Caused by:
  Unable to update https://github.com/smithay//smithay?rev=09e29418e5#09e29418

Caused by:
  object not found - no match for id (09e29418e5d973dd21fc636433cca0b4dc3a17b3); class=Odb (9); code=NotFound (-3)
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: cosmic-epoch-git
```

`just sysext` && `make -C cosmic-comp all` results:
```
➜  cosmic-epoch git:(master) make -C cosmic-comp all
make: Entering directory '/home/dir/workspace/git/cosmic-epoch/cosmic-comp'
cargo build --release
    Updating git repository `https://github.com/smithay//smithay`
error: failed to load source for dependency `smithay`

Caused by:
  Unable to update https://github.com/smithay//smithay?rev=09e29418e5#09e29418

Caused by:
  object not found - no match for id (09e29418e5d973dd21fc636433cca0b4dc3a17b3); class=Odb (9); code=NotFound (-3)
make: *** [Makefile:27: all] Error 101
make: Leaving directory '/home/dir/workspace/git/cosmic-epoch/cosmic-comp'
```

And if you [visit here](https://github.com/Smithay/smithay/tree/09e29418e5d973dd21fc636433cca0b4dc3a17b3) you get:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

**Comment by jokeyrhyme** [comment] 2023-03-01 20:14
The latest commit to cosmic-epoch ( https://github.com/pop-os/cosmic-epoch/commit/75cb3ab49d99fcd7d617cc33a3e1f5c43cb091c1 ) has a submodule reference to this commit of cosmic-comp: https://github.com/pop-os/cosmic-comp/tree/dead320252f5e51ccaedcfbb12e3be9495e8dac4

And I can confirm that this builds without error:

```
$ cd ~/GitHub/pop-os/cosmic-epoch
$ git pull
$ git submodule update --force --init --recursive
$ just clean
$ just sysext
...
Done
```

Which commit of cosmic-comp / cosmic-epoch is used by the AUR? On my own system, `yay` / `paru` don't always properly fetch the correct/latest commits for ...-git AUR packages

**Comment by soloturn** [comment] 2023-03-03 18:18
smithay is a cargo dependency, not in AUR. maybe clean the cargo cache?

**Comment by XV-02** [comment] 2024-02-21 22:28
Due to dormancy, I'm closing this issue as part of cleaning up our tracked issues.

**Closed by XV-02** 2024-02-21 22:28 UTC
Labels: question
