### ISSUE TITLE
Cosmic Apps using wgpu fail with Nvidia graphics.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-comp#264] opened 2024-01-02 07:10 UTC
I stumbled on this while testing both Cosmic-Edit and Cosmic-Term, on a System76 Gaze17 and a Galp5-1650ti. 

Both applications functioned as expected in Pop with Gnome sessions (both X org and Wayland) in all three graphics modes provided by `system76-power` - Integrated, Hybrid, and Discrete.

In a Cosmic session, the applications work as expected in Integrated graphics mode. However, in both Hybrid and Discrete mode they both cause a window to be drawn, but are totally non-responsive. The only way to close the window is to manually terminate the process. 

After back-and-forth with others, it was suggested that the issue might be wgpu. When both Cosmic-Edit and Cosmic-Term were compiled with the wgpu feature disabled, they functioned without issue in Cosmic session in all graphics modes. 

I'm not sure of next-steps for finding debug information, and would appreciate guidance to collect info for this issue.

**Comment by XV-02** [comment] 2024-01-02 14:09
Testing this on a desktop with an Nvidia 1080 and running on nouveau drivers, Cosmic-Term and Cosmic-Edit were both fine, despite being compiled with the wgpu feature present. 

Attempting to run Cosmic on proprietary Nvidia drivers on 10 series cards on desktops results in a thoroughly unresponsive experience, so I haven't tested Cosmic+Desktop Nvidia+Proprietary Nvidia drivers yet. That's another kettle of fish though.

Still, it suggests this might be more directly linked to Nvidia drivers.

**Comment by ids1024** [comment] 2024-01-03 01:51
Apparently this is a known issue with wgpu on recent Nvidia drivers with Wayland. Most likely a driver bug: https://github.com/gfx-rs/wgpu/issues/4775

I can reproduce it on Fedora Rawhide with Gnome Wayland.

**Comment by luccahuguet** [comment] 2024-01-05 16:31
https://github.com/pop-os/cosmic-epoch/issues/168#issuecomment-1878909758

**Comment by anarsoul** [comment] 2024-01-14 04:15
The bug has not been reported to NVIDIA, so I doubt that they are aware

**Comment by gabriele2000** [comment] 2024-01-15 00:20
I've noticed something really weird... I'm using hybrid GPU mode, of course.
I'm a laptop user.

Since today (an update for `cosmic-files`, `cosmic-term` and `cosmic-edit` dropped, I'm in the staging branch) cosmic apps doesn't run at 0.5FPS but at full speed, with a really funny workaround:
![Screenshot_2024-01-15_01-20-10](https://github.com/pop-os/cosmic-comp/assets/12186181/6d891986-36be-4a74-bd35-53a5db8c79f4)

**Comment by gabriele2000** [comment] 2024-01-15 00:24
> The bug has not been reported to NVIDIA, so I doubt that they are aware

https://github.com/NVIDIA/egl-wayland/issues/72#issuecomment-1841775493
It'll be fixed in v550, coming soon, apparently.

**Comment by anarsoul** [comment] 2024-01-15 01:44
> [NVIDIA/egl-wayland#72 (comment)](https://github.com/NVIDIA/egl-wayland/issues/72#issuecomment-1841775493) It'll be fixed in v550, coming soon, apparently.

I don't think it's the same issue. I'm seeing it on Turing GPU (GTX 1650), while the comment says that only pre-Turing GPUs are affected and it should work fine on Turing or later.

**Comment by ids1024** [comment] 2024-01-15 01:51
There's been some debate on wgpu about whether or not this is a driver bug. The Vulcan spec seems a bit vague. But https://github.com/gfx-rs/wgpu/pull/4967 is meant to fix it, and seems like better approach in general.

**Comment by anarsoul** [comment] 2024-01-15 17:48
> There's been some debate on wgpu about whether or not this is a driver bug, or if wgpu is doing something wrong.

My understanding is that it's a driver bug, since fences should work just fine.

**Comment by luccahuguet** [comment] 2024-01-21 22:02
> [pop-os/cosmic-epoch#168 (comment)](https://github.com/pop-os/cosmic-epoch/issues/168#issuecomment-1878909758)
> 
> > I can reproduce #264
> > and it does work only on integrated graphics. Discrete or hybrid does not.
> > my system is the following:
> > OS: Pop!_OS 22.04 LTS x86_64
> > Host: 80YH Lenovo ideapad 320-15IKB
> > Kernel: 6.6.6-76060606-generic
> > Uptime: 12 mins
> > Packages: 2489 (dpkg), 2 (nix-user), 48 (nix-default), 45 (flatpak), 11 (snap)
> > Shell: nu 0.88.1
> > Resolution: 1920x1080
> > DE: COSMIC
> > Theme: Adwaita [GTK3]
> > Icons: Adwaita [GTK3]
> > Terminal: zellij
> > CPU: Intel i7-7500U (4) @ 3.500GHz
> > GPU: NVIDIA GeForce 940MX
> > GPU: Intel HD Graphics 620

I can no longer reproduce this bug

**Comment by RyzenDew** [comment] 2024-01-28 06:50
apps now render properly but will freeze .. with 550 drivers `WGPU_BACKEND=gl` fixes my apps freezing

**Comment by RyzenDew** [comment] 2024-01-29 00:45
https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/967#note_2258144 Confirmed a Driver Bug not a WGPU bug and An nvidia Dev will take a look at the issue! see it helps to report things instead of whining on discord when someone tries to help

**Comment by RyzenDew** [comment] 2024-02-25 00:00
As of the newest stable driver this no longer happens and can be closed @Drakulix

**Closed** 2024-02-26 23:16 UTC

**Comment by soucosmo** [comment] 2024-04-03 16:05
> WGPU_BACKEND=gl

Thanks, its worked for me.
