### ISSUE TITLE
Resizing a window in the tiling mode, causes segfaults

### ISSUE THREAD

**Issue by hojjatabdollahi** [pop-os/cosmic-comp#75] opened 2023-02-15 23:53 UTC
To reproduce, open 3 windows (for example 3 Gnome Terminals) and try to change the size using the mouse. At some point all 3 windows disappear (because they segfaulted). 

Here is the log  Gnome Terminal and Nautilus:
```
pop-os kernel: gnome-terminal-[76947]: segfault at 18 ip 00007f8e11f803b2 sp 00007ffc75458898 error 4 in libgdk-3.so.0.2404.29[7f8e11f04000+83000] likely on CPU 1 (core 1, socket 0)
pop-os kernel: Code: 48 89 c2 e8 b0 88 f8 ff 48 8b bb c0 00 00 00 48 8d 35 2e a8 02 00 e8 cd 9e f8 ff 48 8b 93 c0 00 00 00 5b 48 8d 35 1e ab 05 00 <48> 8b 78 18 e9 a5 7f f8 ff 0f 1f 44 00 00 41 56 41 55 41 54 41 89
pop-os systemd[73789]: gnome-terminal-server.service: Main process exited, code=dumped, status=11/SEGV
pop-os systemd[73789]: gnome-terminal-server.service: Failed with result 'core-dump'.
pop-os systemd[73789]: gnome-terminal-server.service: Consumed 1.774s CPU time.
```
```
Feb 15 16:27:14 pop-os kernel: nautilus[77536]: segfault at 18 ip 00007f46d4da03b2 sp 00007ffe37865228 error 4 in libgdk-3.so.0.2404.29[7f46d4d24000+83000] likely on CPU 0 (core 0, socket 0)
Feb 15 16:27:14 pop-os kernel: Code: 48 89 c2 e8 b0 88 f8 ff 48 8b bb c0 00 00 00 48 8d 35 2e a8 02 00 e8 cd 9e f8 ff 48 8b 93 c0 00 00 00 5b 48 8d 35 1e ab 05 00 <48> 8b 78 18 e9 a5 7f f8 ff 0f 1f 44 00 00 41 56 41 55 41 54 41 89
Feb 15 16:27:15 pop-os cosmic-comp[73986]: restoring focus to: None
```

and here is the output of an Iced window crashing while resizing:
```
[2023-02-15T23:32:30Z ERROR smithay_client_toolkit::event_loop] Error trying to flush the wayland display: Broken pipe (os error 32)
wl_display@1: error 1: invalid arguments for wl_shm@22.create_pool
```

**Comment by Drakulix** [comment] 2023-02-16 12:56
I can reproduce this, but only when gnome-terminal is involved. Are you able to cause this issue with just three nautilus windows?

**Comment by hojjatabdollahi** [comment] 2023-02-16 21:40
Yes. I can reproduce it with 3 nautilus windows. I also tested it with an Iced window, but since it didn't have CSD (can't resize them) I couldn't use 3 Iced windows, I had to use 2 nautilus and one Iced window, but it was the Iced one that crashed not the other 2 nautilus windows. (I have the screen at 2x scale, maybe that helps to recreate this issue easier, since I noticed when resizing sometimes the cursor position was drawn incorrectly when I would start resizing, but that's another issue for another day).

**Comment by hojjatabdollahi** [comment] 2023-02-17 02:52
@Drakulix , I can reliably reproduce it with nautilus. Create 3 nautilus windows, press super+o to change the orientation so you'd have 3 columns, then try to change the size of the middle one.

**Comment by Drakulix** [comment] 2023-02-17 15:50
> @Drakulix , I can reliably reproduce it with nautilus. Create 3 nautilus windows, press super+o to change the orientation so you'd have 3 columns, then try to change the size of the middle one.

Thanks, that helped! I think the error stems from the fact, that in this configuration, the two right window are in the same container, causing them to be resized together. I have a feeling, that in this particular case some calculations of the new sizes go wrong, as other configurations seems to work fine for me, including them being stack horizontally instead of vertically like you are describing.

I want to give the whole resizing logic a large overhaul anyway in the future to make this system fit our various mock-ups better: https://github.com/pop-os/cosmic-epoch/issues/5.
Depending on how difficult it turns out to narrow this one down, I might leave this issue open and focus on the necessary refactoring/rewrite instead. So it might take a little longer until this is truly fixed...

> P.S. My qt applications don't have window decorations, am I missing a config, or is it not implemented yet?

QT apps should use the xdg-decorations protocol, which we do support, so they should get the same treatment as Xwayland apps. Any particular examples of applications that are missing decorations?

**Comment by hojjatabdollahi** [comment] 2023-03-14 17:41
The issue with missing Window Decoration is fixed now.

**Comment by XV-02** [comment] 2024-02-22 18:35
Closing, as I don't see either problem mentioned in this issue on current master builds of Cosmic DE.

**Closed by XV-02** 2024-02-22 18:35 UTC
