### ISSUE TITLE
(Bug) Drag and drop files between windows freeze the compositor

### ISSUE THREAD

**Issue by hardBSDk** [pop-os/cosmic-comp#625] opened 2024-07-17 20:43 UTC
I dragged files from GNOME Nautilus and dropped on Firefox to upload to GitHub, the compositor freeze.

It don't freeze the audio server because I was listening to music and it continue to play.

## How To Reproduce

- Open two tiled windows
- Drag and drop files between them
- If nothing happens try GTK programs

**Comment by atagen** [comment] 2024-07-18 01:28
dupe of #492

**Closed** 2024-07-18 14:28 UTC
