### ISSUE TITLE
Non-autotiled top and bottom half tiled windows start at left screen edge when untiled by dragging

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-comp#371] opened 2024-03-20 13:41 UTC
When a window is top or bottom half tiled, untiling it by dragging the header bar places it next to the left screen edge, instead of keeping its relative position to the clicked point in the header.
This can lead to the cursor being quite detached from the window, if dragging is started on the right side of the header bar.

**Comment by ryanabx** [comment] 2024-03-20 15:33
Does this also occur when you half tile with Super + Shift + Up/Down?

**Comment by git-f0x** [comment] 2024-03-20 15:44
Indeed it does! So it's probably not related to your mouse region tiling PR.

**Comment by WatchMkr** [comment] 2024-05-21 03:42
Does this still happen. I can't reproduce.

**Comment by git-f0x** [comment] 2024-05-21 05:37
It does, at least on my end.

https://github.com/pop-os/cosmic-comp/assets/150025636/f33b94f6-3a7b-4811-9d3a-76b19657db32

**Comment by git-f0x** [comment] 2024-05-21 06:27
Happens with all apps.

Have only 1 display, so not sure.

Not sure what scenarios other than dragging it (don't know of another way to unsnap windows, without maximizing then unmaximizing).

**Comment by WatchMkr** [comment] 2024-05-21 18:24
Your video helped. I can reproduce that. Thanks.

**Comment by WatchMkr** [comment] 2024-05-21 18:29
It's very similar to the issue where apps with SSDs remain as long as the window is when pulled out of top-half tiled position.

**Comment by WatchMkr** [comment] 2024-05-22 12:51
Perhaps related https://github.com/pop-os/cosmic-comp/issues/470

**Comment by Drakulix** [comment] 2024-06-28 10:32
Fixed by https://github.com/pop-os/cosmic-comp/commit/5662a0f219945c6c220b8785da53d67dc7628f46

**Closed by Drakulix** 2024-06-28 10:32 UTC
Labels: needs testing
