### ISSUE TITLE
cosmic-comp crashes when you turn on a single display

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/cosmic-comp#558] opened 2024-06-14 16:14 UTC
I turn off my monitor at night. Music playing in the background continues (and session lives) until I turn the monitor back on.

**Comment by addy419** [comment] 2024-06-15 20:56
@thomas-zimmerman I have been facing the same issue.

**Comment by Quackdoc** [comment] 2024-06-16 22:30
what commit hash are you running? I was running into that issue a while ago but it solved itself after updating, as a temporary work around I was disabling the display first, then turning off the display, turn on display, then enabled it using cosmic-randr

**Comment by WatchMkr** [comment] 2024-06-17 16:12
Duplicate of https://github.com/pop-os/cosmic-comp/issues/57

**Closed by WatchMkr** 2024-06-17 16:12 UTC
