### ISSUE TITLE
Wacom not working

### ISSUE THREAD

**Issue by ricc3** [pop-os/cosmic-comp#825] opened 2024-09-06 10:21 UTC
I have a Wacom Intuos ctl-490 graphics tablet [ data with  tablet ].

system sees table:
```
sudo libinput debug-events
-event15  DEVICE_ADDED            Wacom Intuos S 2 Pen              seat0 default group6  cap:T  size 152x95mm
-event16  DEVICE_ADDED            Wacom Intuos S 2 Pad              seat0 default group6  cap:P buttons:4 strips:0 rings:0 mode groups:1
```

As far as I can see, the terminal records clicks as well as pen movement on the tablet, but I can't move the pointer either on the desktop or in any application. I checked in Blender downloaded from the website and in Xournal++

**Comment by leviport** [comment] 2024-09-06 14:45
Duplicate of https://github.com/pop-os/cosmic-comp/issues/313

**Closed by leviport** 2024-09-06 14:45 UTC
